project_id = "sgggqrcwfcbtyianduyo"

[functions.send-requirement-notification]
verify_jwt = false

[functions.sync-requirements-to-google-sheets]
verify_jwt = false

[functions.sync-to-google-sheets]
verify_jwt = false
